package forge.web;

import forge.trackable.TrackableProperty;
import forge.trackable.TrackableTypes;
import forge.trackable.TrackableTypes.TrackableType;

import java.lang.reflect.Field;
import java.lang.reflect.ParameterizedType;
import java.lang.reflect.RecordComponent;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.Collection;
import java.util.IdentityHashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.StringJoiner;

/**
 * Writes src/main/ts/protocol.gen.ts: the protocol's records ({@link ToBrowser}, {@link FromBrowser}) as
 * TypeScript, and the game objects' properties as {@link JsonCodec} encodes them. {@link ProtocolTypesTest} fails
 * when the file is stale, so neither side can change a field without the other hearing of it.
 */
final class ProtocolTypes {
    static final String FILE = "protocol.gen.ts";

    private final StringBuilder out = new StringBuilder();
    private final Map<Class<?>, String> declared = new LinkedHashMap<>();
    private final List<Class<?>> pending = new ArrayList<>();

    private ProtocolTypes() {
    }

    static String generate() {
        return new ProtocolTypes().write();
    }

    private String write() {
        out.append("// Generated by ProtocolTypesTest from forge.web.ToBrowser, forge.web.FromBrowser and\n")
                .append("// forge.trackable.TrackableProperty. Do not edit: change the Java and regenerate (see README.md).\n\n");
        out.append("// ---- Server to browser ----\n\n");
        for (final Class<? extends Record> m : ToBrowser.MESSAGES) {
            record(m, "  t: '" + m.getAnnotation(Wire.Message.class).value() + "';\n");
        }
        out.append("// ---- Requests: questions the game waits on, answered with {t: 'reply', id, value} ----\n\n");
        for (final Class<? extends Record> r : ToBrowser.REQUESTS) {
            final String kind = r.getAnnotation(Wire.Request.class).value();
            record(r, "  t: 'request';\n  id: number;\n" + (kind.isEmpty() ? "" : "  kind: '" + kind + "';\n"));
        }
        union("Request", ToBrowser.REQUESTS);
        final List<Class<? extends Record>> server = new ArrayList<>(ToBrowser.MESSAGES);
        server.addAll(ToBrowser.REQUESTS);
        union("ServerMessage", server);
        out.append("// ---- Browser to server ----\n\n");
        for (final Class<? extends Record> c : FromBrowser.COMMANDS) {
            final String t = c.getAnnotation(Wire.Command.class).value();
            record(c, t.isEmpty() ? "" : "  t: '" + t + "';\n");
        }
        union("ClientMessage", FromBrowser.COMMANDS);
        out.append("// ---- Game events: what happened, carried by the state message that shows its result ----\n\n");
        for (final Class<? extends Record> e : ToBrowser.EVENTS) {
            record(e, "  kind: '" + e.getAnnotation(Wire.Event.class).value() + "';\n");
        }
        union("GameEvent", ToBrowser.EVENTS);
        drain();
        out.append("// ---- Game objects: TrackableProperty values as JsonCodec encodes them ----\n\n");
        trackedProps();
        return out.toString();
    }

    private void union(final String name, final Collection<Class<? extends Record>> members) {
        final StringJoiner j = new StringJoiner("\n  | ", "export type " + name + " =\n  | ", ";\n\n");
        members.forEach(m -> j.add(m.getSimpleName()));
        out.append(j);
    }

    /** A record as an interface; the records it uses are written after it. */
    private void record(final Class<?> type, final String head) {
        declared.put(type, type.getSimpleName());
        out.append("export interface ").append(type.getSimpleName()).append(" {\n").append(head);
        for (final RecordComponent c : Wire.components(type)) {
            final boolean optional = c.isAnnotationPresent(Wire.Nullable.class);
            final Wire.Ts override = c.getAnnotation(Wire.Ts.class);
            final boolean discriminant = c.getName().equals("t") || c.getName().equals("kind");
            final String ts = override != null ? override.value()
                    : discriminant && c.getType().isEnum() ? literals(c.getType()) : tsOf(c.getGenericType());
            out.append("  ").append(Wire.nameOf(c)).append(optional ? "?: " : ": ").append(ts).append(";\n");
        }
        out.append("}\n\n");
    }

    /** Records and enums reached through components, written once each. */
    private void drain() {
        while (!pending.isEmpty()) {
            final Class<?> next = pending.remove(0);
            if (next.isEnum()) {
                out.append("export type ").append(next.getSimpleName()).append(" = ").append(literals(next)).append(";\n\n");
            } else {
                record(next, "");
            }
        }
    }

    private String named(final Class<?> type) {
        final String existing = declared.get(type);
        if (existing != null) {
            return existing;
        }
        for (final String name : declared.values()) {
            if (name.equals(type.getSimpleName())) {
                throw new IllegalStateException("Two protocol types are named " + name + "; TypeScript needs one of them renamed");
            }
        }
        declared.put(type, type.getSimpleName());
        pending.add(type);
        return type.getSimpleName();
    }

    private static String literals(final Class<?> enumType) {
        final StringJoiner j = new StringJoiner(" | ");
        for (final Object constant : enumType.getEnumConstants()) {
            j.add("'" + ((Enum<?>) constant).name() + "'");
        }
        return j.toString();
    }

    private String tsOf(final Type type) {
        if (type instanceof ParameterizedType p) {
            final Class<?> raw = (Class<?>) p.getRawType();
            final Type[] args = p.getActualTypeArguments();
            if (Collection.class.isAssignableFrom(raw)) {
                return array(tsOf(args[0]));
            }
            if (Map.class.isAssignableFrom(raw)) {
                return "Record<string, " + tsOf(args[1]) + ">";
            }
            throw new IllegalStateException("No TypeScript for " + type);
        }
        final Class<?> c = (Class<?>) type;
        if (c == boolean.class || c == Boolean.class) {
            return "boolean";
        }
        if (c.isPrimitive() || Number.class.isAssignableFrom(c)) {
            return "number";
        }
        if (c == String.class) {
            return "string";
        }
        if (c == com.google.gson.JsonObject.class) {
            return "Record<string, unknown>";
        }
        if (com.google.gson.JsonElement.class.isAssignableFrom(c)) {
            return "unknown";
        }
        if (c.isEnum() || c.isRecord()) {
            return named(c);
        }
        throw new IllegalStateException("No TypeScript for " + type);
    }

    private static String array(final String element) {
        return element.contains(" ") ? "(" + element + ")[]" : element + "[]";
    }

    // ---- Game objects ----------------------------------------------------------------------------------------

    private void trackedProps() {
        // The enum table fills as TrackableProperty's constants are made, so they are made first
        final TrackableProperty[] props = TrackableProperty.values();
        final Map<TrackableType<?>, Class<?>> enums = enumTypes();
        named(ToBrowser.Ref.class);
        out.append("/** One attack: who attacks what, and who blocks it. */\n")
                .append("export interface CombatBand {\n")
                .append("  attackers: (Ref | null)[] | null;\n")
                .append("  defender: Ref | null;\n")
                .append("  blockers: (Ref | null)[] | null;\n")
                .append("  plannedBlockers: (Ref | null)[] | null;\n")
                .append("}\n\n")
                .append("export interface CommanderValue {\n  card: Ref;\n  value: number;\n}\n\n")
                .append("export interface KeywordText {\n  title: string;\n  reminder: string;\n  icon?: string;\n}\n\n")
                .append("/** Every property any game object can carry. A property still at its default is left out. */\n")
                .append("export interface TrackedProps {\n");
        final StringBuilder enumAliases = new StringBuilder();
        for (final TrackableProperty prop : props) {
            out.append("  ").append(prop.name()).append("?: ").append(tsOf(prop, enums, enumAliases)).append(";\n");
        }
        out.append("}\n\n");
        out.append(enumAliases);
        out.append("/** A change to an object: a property set to null has gone back to its default. */\n")
                .append("export type TrackedDelta = { [K in keyof TrackedProps]?: TrackedProps[K] | null };\n");
    }

    /** Mirrors JsonCodec.encodeValue: the JSON each kind of property value becomes. */
    private String tsOf(final TrackableProperty prop, final Map<TrackableType<?>, Class<?>> enums, final StringBuilder aliases) {
        final TrackableType<?> t = prop.getType();
        if (prop == TrackableProperty.CommanderDamage || prop == TrackableProperty.CommanderCast) {
            return "CommanderValue[]";
        }
        if (t == TrackableTypes.BooleanType) {
            return "boolean";
        }
        if (t == TrackableTypes.IntegerType || t == TrackableTypes.FloatType || t == TrackableTypes.ColorSetType) {
            return "number";
        }
        if (t == TrackableTypes.StringType || t == TrackableTypes.ManaCostType || t == TrackableTypes.CardTypeViewType) {
            return "string";
        }
        if (t == TrackableTypes.CardViewType || t == TrackableTypes.PlayerViewType || t == TrackableTypes.StackItemViewType
                || t == TrackableTypes.CardStateViewType || t == TrackableTypes.GameEntityViewType) {
            return "Ref";
        }
        if (t == TrackableTypes.CardViewCollectionType || t == TrackableTypes.PlayerViewCollectionType
                || t == TrackableTypes.StackItemViewListType) {
            return "(Ref | null)[]";
        }
        if (t == TrackableTypes.CombatViewType) {
            return "CombatBand[]";
        }
        if (t == TrackableTypes.StringListType || t == TrackableTypes.StringSetType) {
            return "string[]";
        }
        if (t == TrackableTypes.IntegerSetType) {
            return "number[]";
        }
        if (t == TrackableTypes.StringMapType) {
            return "Record<string, string>";
        }
        if (t == TrackableTypes.IntegerMapType || t == TrackableTypes.ManaMapType || t == TrackableTypes.CounterMapType) {
            return "Record<string, number>";
        }
        if (t == TrackableTypes.GenericMapType || t == TrackableTypes.ObjectType) {
            return "unknown";
        }
        if (t == TrackableTypes.KeywordCollectionViewType) {
            return "KeywordText[]";
        }
        if (t == TrackableTypes.IPaperCardType) {
            return "{ name: string; imageKey: string }";
        }
        final Class<?> enumType = enums.get(t);
        if (enumType != null) {
            final String name = enumType.getSimpleName();
            if (!declared.containsKey(enumType)) {
                declared.put(enumType, name);
                aliases.append("export type ").append(name).append(" = ").append(literals(enumType)).append(";\n\n");
            }
            return name;
        }
        if (enums.isEmpty()) {
            return "string";
        }
        throw new IllegalStateException("No TypeScript for property " + prop + ": add its JSON form to JsonCodec and here");
    }

    /**
     * Which enum each EnumType property holds. TrackableTypes keeps that only in a private table, so it is read by
     * reflection; if Forge ever changes the table, an enum property is typed by the constants' names being strings.
     */
    private static Map<TrackableType<?>, Class<?>> enumTypes() {
        final Map<TrackableType<?>, Class<?>> out = new IdentityHashMap<>();
        try {
            final Field f = TrackableTypes.class.getDeclaredField("enumTypes");
            f.setAccessible(true);
            final Map<?, ?> table = (Map<?, ?>) f.get(null);
            table.forEach((k, v) -> out.put((TrackableType<?>) v, (Class<?>) k));
        } catch (final ReflectiveOperationException | RuntimeException e) {
            // Typed as string below
        }
        return out;
    }
}
