// Generated by ProtocolTypesTest from forge.web.ToBrowser, forge.web.FromBrowser and
// forge.trackable.TrackableProperty. Do not edit: change the Java and regenerate (see README.md).

// ---- Server to browser ----

export interface Hello {
  t: 'hello';
  inMatch: boolean;
  inLobby: boolean;
  joining: boolean;
  spectating: boolean;
  host: boolean;
  canClaimHost: boolean;
  networked: boolean;
  playerName?: string;
  avatars: number[];
  sleeves: number[];
  avatarCount: number;
  sleeveCount: number;
  sleeveArt: SavedSleeveArt[];
  inEvent: boolean;
  eventPool?: string;
  sealedPools: number;
  eventKind?: string;
  drafting: boolean;
  draftPools: number;
  settings: ServerSettings;
}

export interface Presence {
  t: 'presence';
  people: Person[];
}

export interface ErrorMessage {
  t: 'error';
  message: string;
}

export interface Notice {
  t: 'notice';
  title?: string;
  message?: string;
  error: boolean;
}

export interface Decks {
  t: 'decks';
  decks: DeckSummary[];
  cardFormats: string[];
  cardPool?: string;
}

export interface DeckDetailsMessage {
  t: 'deckDetails';
  deck: DeckDetails;
}

export interface ExtraChoices {
  t: 'extraChoices';
  section: string;
  index: number;
  choices: ExtraChoice[];
}

export interface LobbyMessage {
  t: 'lobby';
  table?: LobbyTable;
}

export interface Addresses {
  t: 'addresses';
  list: Address[];
}

export interface ChatLine {
  t: 'chat';
  from?: string;
  text: string;
}

export interface CardSearch {
  t: 'cardSearch';
  names: string[];
}

export interface Printings {
  t: 'printings';
  name: string;
  printings: Printing[];
}

export interface HostChoice {
  t: 'hostChoice';
  id: number;
  kind: string;
  message?: string;
  min: number;
  max: number;
  options: string[];
}

export interface StateMessage {
  t: 'state';
  full: boolean;
  seq: number;
  root: number;
  newObjects: Record<string, TrackedProps>;
  deltas: Record<string, TrackedDelta>;
  visible: number[];
  localPlayers: number[];
  events: GameEvent[];
}

export interface Prompt {
  t: 'prompt';
  message: string;
  priority: boolean;
  card?: Ref;
  ok: PromptButton;
  cancel: PromptButton;
  focusOk: boolean;
  paying: boolean;
  selectable: Ref[];
  selectableMin: number;
  selectablePlayers: Ref[];
  highlighted: number[];
  starterChoice?: string;
}

export interface Playable {
  t: 'playable';
  cards: Ref[];
  autoTap: Ref[];
}

export interface Zones {
  t: 'zones';
  show: ShownZone[];
}

export interface Controls {
  t: 'controls';
  myStops: PhaseType[];
  otherStops: PhaseType[];
  autoPass: boolean;
  dayTime?: string;
  marker?: TurnMarker;
  untilEndOfTurn: boolean;
  untilStackEmpty: boolean;
  settings: ServerSettings;
}

export interface DevState {
  t: 'devState';
  unlimitedLands: boolean;
  viewAll: boolean;
}

export interface DevDump {
  t: 'devDump';
  text: string;
}

export interface LogMessage {
  t: 'log';
  full: boolean;
  entries: LogEntry[];
}

export interface Detail {
  t: 'detail';
  key: number;
  faces: CardFace[];
}

export interface PlayerDetail {
  t: 'playerDetail';
  key: number;
  name?: string;
  lines: string[];
}

export interface StackMenu {
  t: 'stackMenu';
  key: number;
  autoYield?: boolean;
  trigger?: TriggerDecision;
}

export interface Sound {
  t: 'sound';
  name: string;
  sync: boolean;
}

export interface Flash {
  t: 'flash';
}

export interface GameOver {
  t: 'gameOver';
}

export interface DrawOffer {
  t: 'drawOffer';
  offerer?: Ref;
  open: boolean;
  mine: boolean;
  waitingOnMe: boolean;
}

export interface AutoDecisions {
  t: 'autoDecisions';
  entries: AutoDecision[];
  yieldsOff: boolean;
  triggersOff: boolean;
}

export interface CataloguePage {
  t: 'catalogue';
  request: number;
  rows: CatalogueRow[];
  total: number;
  offset: number;
  hiddenBySwitch: number;
  ranked: boolean;
}

export interface EditorMessage {
  t: 'editor';
  state?: EditorState;
}

export interface ImportResult {
  t: 'importResult';
  request: number;
  lines: ImportLine[];
  problems: ImportProblem[];
  summary: ImportSummary;
  name?: string;
  fetched?: Fetched;
}

export interface NameTaken {
  t: 'nameTaken';
  name: string;
}

export interface DeviceDeck {
  t: 'deviceDeck';
  id: string;
  text?: string;
  format: string;
}

export interface CardPoolDetails {
  t: 'cardPoolDetails';
  lines: CardPoolLine[];
}

export interface LimitedOptions {
  t: 'limitedOptions';
  blocks: SealedBlock[];
  fantasyBlocks: SealedBlock[];
  prereleases: LimitedEdition[];
  templates: string[];
  draftBlocks: DraftBlockOption[];
  draftFantasyBlocks: DraftBlockOption[];
  cubes: string[];
  themes: string[];
  lastCube?: string;
}

export interface LimitedPools {
  t: 'limitedPools';
  sealed: PoolRow[];
  draft: PoolRow[];
}

export interface DraftState {
  t: 'draft';
  step: number;
  product: string;
  pack: number;
  packs: number;
  pick: number;
  packSize: number;
  direction: number;
  seats: DraftSeat[];
  cards: DraftCard[];
  picks: DraftCard[];
  moved: number[];
  clockSeconds: number;
  clockLeftMillis: number;
  log: string[];
  done: boolean;
}

export interface LimitedResult {
  t: 'limitedResult';
  round: number;
  rounds: number;
  wins: number;
  losses: number;
  matchOver: boolean;
  wonMatch: boolean;
  nextRound: boolean;
}

// ---- Requests: questions the game waits on, answered with {t: 'reply', id, value} ----

export interface ChoicesRequest {
  t: 'request';
  id: number;
  kind: 'choices' | 'reveal';
  message?: string;
  min: number;
  max: number;
  options: RequestOption[];
  selected: number[];
  stackKeys?: number[];
  atX?: number;
  atY?: number;
  default: number[];
}

export interface OrderRequest {
  t: 'request';
  id: number;
  kind: 'order';
  title?: string;
  top?: string;
  min: number;
  max: number;
  options: RequestOption[];
  selected: number[];
  remember: boolean;
  card?: Ref;
  default: OrderAnswer;
}

export interface ManipulateRequest {
  t: 'request';
  id: number;
  kind: 'manipulate';
  title?: string;
  options: RequestOption[];
  movable: number[];
  toTop: boolean;
  toBottom: boolean;
  default: number[];
}

export interface OptionRequest {
  t: 'request';
  id: number;
  kind: 'option';
  title?: string;
  message?: string;
  card?: Ref;
  labels: string[];
  default: number;
}

export interface TextRequest {
  t: 'request';
  id: number;
  kind: 'text';
  title?: string;
  message?: string;
  initial?: string;
  numeric: boolean;
  default?: string;
}

export interface DistributeRequest {
  t: 'request';
  id: number;
  kind: 'distribute';
  message?: string;
  amount: number;
  perMin: number;
  options: RequestOption[];
  card?: Ref;
  maySkip: boolean;
  default: number[];
}

export interface SideboardRequest {
  t: 'request';
  id: number;
  kind: 'sideboard';
  message?: string;
  entries: SideboardEntry[];
  main: number[];
  default: number[];
}

export interface AutoPassRequest {
  t: 'request';
  id: number;
  kind: 'autoPass';
  delay: number;
  default: boolean;
}

export type Request =
  | ChoicesRequest
  | OrderRequest
  | ManipulateRequest
  | OptionRequest
  | TextRequest
  | DistributeRequest
  | SideboardRequest
  | AutoPassRequest;

export type ServerMessage =
  | Hello
  | Presence
  | ErrorMessage
  | Notice
  | Decks
  | DeckDetailsMessage
  | ExtraChoices
  | LobbyMessage
  | Addresses
  | ChatLine
  | CardSearch
  | Printings
  | HostChoice
  | StateMessage
  | Prompt
  | Playable
  | Zones
  | Controls
  | DevState
  | DevDump
  | LogMessage
  | Detail
  | PlayerDetail
  | StackMenu
  | Sound
  | Flash
  | GameOver
  | DrawOffer
  | AutoDecisions
  | CataloguePage
  | EditorMessage
  | ImportResult
  | NameTaken
  | DeviceDeck
  | CardPoolDetails
  | LimitedOptions
  | LimitedPools
  | DraftState
  | LimitedResult
  | ChoicesRequest
  | OrderRequest
  | ManipulateRequest
  | OptionRequest
  | TextRequest
  | DistributeRequest
  | SideboardRequest
  | AutoPassRequest;

// ---- Browser to server ----

export interface Bare {
  t: 'decks' | 'claimHost' | 'join' | 'lobby' | 'invite' | 'leaveLobby' | 'addresses' | 'cardPoolDetails' | 'netDecks' | 'leave' | 'quit' | 'limitedLeave' | 'poolClose' | 'draftDiscard' | 'gauntletNext' | 'gauntletRestart' | 'eventStart' | 'ok' | 'cancel' | 'endTurn' | 'autoPass' | 'undo' | 'concede';
}

export interface SetName {
  t: 'setName';
  name: string;
  avatar?: number;
}

export interface Say {
  t: 'chat';
  text: string;
}

export interface Ready {
  t: 'ready';
  ready: boolean;
}

export interface SeatCommand {
  t: 'openSeat' | 'aiSeat' | 'removeSeat';
  index: number;
}

export interface SetSeat {
  t: 'setSeat';
  index: number;
  name?: string;
  deck?: string;
  avatar?: number;
  sleeve?: number;
}

export interface SetFormat {
  t: 'setFormat';
  format: string;
}

export interface SetCardPool {
  t: 'setCardPool';
  cardPool?: string;
}

export interface SetVariant {
  t: 'setVariant';
  variant: string;
  on: boolean;
}

export interface SetArchenemy {
  t: 'setArchenemy';
  index: number;
}

export interface SetSeatExtra {
  t: 'setSeatExtra';
  index: number;
  section: string;
  choice: string;
}

export interface AskExtraChoices {
  t: 'extraChoices';
  index: number;
  section: string;
}

export interface AskDeckDetails {
  t: 'deckDetails';
  key: string;
}

export interface HostChoiceAnswer {
  t: 'hostChoice';
  id: number;
  value: number[];
}

export interface SearchCards {
  t: 'cardSearch';
  query: string;
}

export interface AskPrintings {
  t: 'printings';
  name: string;
  cardPool?: string;
}

export interface SleeveArt {
  t: 'sleeveArt';
  index: number;
  key: string;
  offset: number;
}

export interface Start {
  t: 'start';
  spectate: boolean;
}

export interface Reply {
  t: 'reply';
  id: number;
  value: unknown;
}

export interface SelectCard {
  t: 'selectCard';
  key: number;
  menu: boolean;
  x: number;
  y: number;
}

export interface KeyCommand {
  t: 'selectPlayer' | 'detail' | 'playerDetail' | 'stackMenu';
  key: number;
}

export interface StackYield {
  t: 'stackYield';
  key: number;
  action: YieldAction;
}

export interface PhaseCommand {
  t: 'toggleStop' | 'toggleMarker';
  phase: PhaseType;
  mine: boolean;
}

export interface SetStops {
  t: 'setStops';
  mine: boolean;
  phases: PhaseType[];
}

export interface UseMana {
  t: 'useMana';
  color: number;
}

export interface SetSetting {
  t: 'setSetting';
  key: string;
  value: string;
}

export interface Dev {
  t: 'dev';
  action: DevAction;
  text?: string;
}

export interface NextGame {
  t: 'nextGame';
  decision: NextGameDecision;
}

export interface DrawOfferCommand {
  t: 'drawOffer';
  action: Action;
}

export interface AutoDecisionCommand {
  t: 'autoDecisions';
  action: AutoDecisionAction;
  key?: string;
  on: boolean;
}

export interface BrowseFormat {
  t: 'browseFormat';
  format: string;
}

export interface EditorOpen {
  t: 'editorOpen';
  key?: string;
  newFormat?: string;
  seat?: number;
  copy: boolean;
}

export interface EditorBare {
  t: 'editorClose' | 'editorUndo';
}

export interface EditorEdit {
  t: 'editorEdit';
  op: EditOp;
  name?: string;
  from?: DeckSection;
  to?: DeckSection;
  count: number;
  printings?: CountedName[];
  lands?: CountedName[];
}

export interface EditorRename {
  t: 'editorRename';
  name: string;
}

export interface EditorCheck {
  t: 'editorCheck';
  format: string;
  cardPool?: string;
  unrestricted: boolean;
}

export interface EditorDeck {
  t: 'editorDeck';
  op: DeckOp;
}

export interface CatalogueQuery {
  t: 'catalogue';
  request: number;
  text: string;
  colours: string;
  type: string;
  mv: string;
  sort: string;
  offset: number;
  showAll: boolean;
}

export interface ImportRead {
  t: 'importRead';
  request: number;
  text: string;
  format: string;
  cardPool?: string;
  unrestricted: boolean;
}

export interface ImportFetch {
  t: 'importFetch';
  request: number;
  url: string;
}

export interface ImportCommit {
  t: 'importCommit';
  text: string;
  name: string;
  format: string;
  cardPool?: string;
  unrestricted: boolean;
  action: ImportAction;
  seat?: number;
  url?: string;
  clash?: Clash;
}

export interface DeviceDecks {
  t: 'deviceDecks';
  decks: DeviceDeckText[];
}

export interface LimitedOpen {
  t: 'limitedOpen';
  kind: string;
  resume: boolean;
}

export interface SealedCreate {
  t: 'sealedCreate';
  product: string;
  block?: string;
  combo?: string;
  edition?: string;
  template?: string;
  cubeId?: string;
  packs: number;
  name: string;
  replace: boolean;
}

export interface PoolOpen {
  t: 'poolOpen';
  name: string;
}

export interface PoolEdit {
  t: 'poolEdit';
  name: string;
}

export interface PoolDelete {
  t: 'poolDelete';
  name: string;
}

export interface PoolPlay {
  t: 'poolPlay';
  name: string;
  mode?: string;
  opponent: number;
  count: number;
  games: number;
}

export interface DraftStart {
  t: 'draftStart';
  product: string;
  block?: string;
  combo?: string;
  cube?: string;
  theme?: string;
  cubeId?: string;
}

export interface DraftPick {
  t: 'draftPick';
  step: number;
  index: number;
}

export interface DraftSave {
  t: 'draftSave';
  name: string;
  replace: boolean;
}

export interface SetLimited {
  t: 'setLimited';
  kind?: string;
}

export interface EventSetup {
  t: 'eventSetup';
  product: string;
  block?: string;
  combo?: string;
  edition?: string;
  template?: string;
  cube?: string;
  theme?: string;
  cubeId?: string;
  packs: number;
  podSize: number;
  pickRule?: string;
  timer: number;
  grace: number;
}

export interface BenchSeat {
  t: 'benchSeat';
  index: number;
  benched: boolean;
}

export interface SetPlayerCount {
  t: 'setPlayerCount';
  count: number;
}

export interface SetMatchLength {
  t: 'setMatchLength';
  games: number;
}

export interface EventDecksOnly {
  t: 'eventDecksOnly';
  on: boolean;
}

export interface EventHostAgain {
  t: 'eventHostAgain';
  eventId: string;
}

export type ClientMessage =
  | Bare
  | SetName
  | Say
  | Ready
  | SeatCommand
  | SetSeat
  | SetFormat
  | SetCardPool
  | SetVariant
  | SetArchenemy
  | SetSeatExtra
  | AskExtraChoices
  | AskDeckDetails
  | HostChoiceAnswer
  | SearchCards
  | AskPrintings
  | SleeveArt
  | Start
  | Reply
  | SelectCard
  | KeyCommand
  | StackYield
  | PhaseCommand
  | SetStops
  | UseMana
  | SetSetting
  | Dev
  | NextGame
  | DrawOfferCommand
  | AutoDecisionCommand
  | BrowseFormat
  | EditorOpen
  | EditorBare
  | EditorEdit
  | EditorRename
  | EditorCheck
  | EditorDeck
  | CatalogueQuery
  | ImportRead
  | ImportFetch
  | ImportCommit
  | DeviceDecks
  | LimitedOpen
  | SealedCreate
  | PoolOpen
  | PoolEdit
  | PoolDelete
  | PoolPlay
  | DraftStart
  | DraftPick
  | DraftSave
  | SetLimited
  | EventSetup
  | BenchSeat
  | SetPlayerCount
  | SetMatchLength
  | EventDecksOnly
  | EventHostAgain;

// ---- Game events: what happened, carried by the state message that shows its result ----

export interface CardMoved {
  kind: 'cardMoved';
  card: Ref;
  from?: Place;
  to?: Place;
}

export interface CardDamaged {
  kind: 'cardDamaged';
  card: Ref;
  source?: Ref;
  amount: number;
}

export interface PlayerDamaged {
  kind: 'playerDamaged';
  player: Ref;
  source?: Ref;
  amount: number;
  combat: boolean;
}

export interface AttackersDeclared {
  kind: 'attackersDeclared';
  player: Ref;
  attacks: Attack[];
}

export interface Shuffled {
  kind: 'shuffled';
  player: Ref;
}

export interface GameStarted {
  kind: 'gameStarted';
  first: Ref;
}

export type GameEvent =
  | CardMoved
  | CardDamaged
  | PlayerDamaged
  | AttackersDeclared
  | Shuffled
  | GameStarted;

export interface SavedSleeveArt {
  key: string;
  offset: number;
}

export interface ServerSettings {
  interruptAttackers: boolean;
  interruptOpponentSpell: boolean;
  interruptTargeting: boolean;
  interruptTriggers: boolean;
  interruptMassRemoval: boolean;
  autoTapPreview: boolean;
  autoYieldMode: string;
  logDetail: GameLogVerbosity;
  arrows: string;
  devMode: boolean;
  highlightColor: string;
  soundVolume: number;
  musicVolume: number;
}

export interface Person {
  name: string;
  avatar: number;
  doing: string;
  host: boolean;
}

export interface DeckSummary {
  key: string;
  name: string;
  source: string;
  colors: string;
  generated?: boolean;
  note?: string;
  main?: number;
  sideboard?: number;
  problem?: string;
  legalIn?: string[];
  formats?: string;
  sleeveArt?: string;
  sleeveOffset?: number;
  readOnly?: boolean;
  linked?: string;
  sourceUrl?: string;
  synced?: number;
}

export interface DeckDetails {
  key: string;
  name: string;
  problem?: string;
  colors: string;
  stats: DeckStats;
  main: EditorGroup[];
  sideboard: EditorCard[];
  sleeveArt?: string;
  sleeveOffset: number;
}

export interface ExtraChoice {
  key: string;
  label: string;
  count?: number;
  problem?: string;
  image?: string;
  hand?: number;
  life?: number;
}

export interface LobbyTable {
  host: boolean;
  mySeat: number;
  shareable: boolean;
  format: string;
  formats: Format[];
  cardPool?: string;
  cardPools: CardPoolGroup[];
  casualVariants: Format[];
  variantsOn: string[];
  maxSeats: number;
  gamesPerMatch: number;
  seats: Seat[];
  problems: string[];
  canStart: boolean;
  limited?: LimitedTable;
}

export interface Address {
  label: string;
  url: string;
}

export interface Printing {
  name: string;
  edition: string;
  key: string;
  setName: string;
  year: number;
  problem?: string;
}

export interface Ref {
  ref: number;
}

export interface PromptButton {
  label: string;
  enabled: boolean;
}

export interface ShownZone {
  player: Ref;
  zone: ZoneType;
}

export type PhaseType = 'UNTAP' | 'UPKEEP' | 'DRAW' | 'MAIN1' | 'COMBAT_BEGIN' | 'COMBAT_DECLARE_ATTACKERS' | 'COMBAT_DECLARE_BLOCKERS' | 'COMBAT_FIRST_STRIKE_DAMAGE' | 'COMBAT_DAMAGE' | 'COMBAT_END' | 'MAIN2' | 'END_OF_TURN' | 'CLEANUP';

export interface TurnMarker {
  phase: PhaseType;
  mine: boolean;
}

export interface LogEntry {
  type: GameLogEntryType;
  message: string;
  card?: number;
  imageKey?: string;
}

export interface CardFace {
  name?: string;
  cost: string;
  type: string;
  pt?: string;
  text: string;
  imageKey?: string;
}

export type TriggerDecision = 'ASK' | 'ACCEPT' | 'DECLINE';

export interface AutoDecision {
  key: string;
  kind: 'yield' | 'accept' | 'decline';
}

export interface CatalogueRow {
  name: string;
  image: string;
  cost: string;
  mv: number;
  colors: string;
  type: string;
  pt?: string;
  heading: string;
  inDeck: number;
  problem?: string;
}

export interface EditorState {
  name: string;
  check: string;
  format: string;
  cardPool?: string;
  unrestricted: boolean;
  target: string;
  copyOf?: string;
  commanders: EditorCard[];
  commanderWanted: boolean;
  identity: string;
  main: EditorGroup[];
  sideboard: EditorCard[];
  lands: EditorLand[];
  stats: DeckStats;
  verdict?: string;
  problemCount: number;
  canUndo: boolean;
  landed?: string;
  onSeat: boolean;
  limited: boolean;
  landSet?: string;
  landSets: LandSet[];
}

export interface ImportLine {
  kind: string;
}

export interface ImportProblem {
  line: number;
  title: string;
  detail: string;
  fixes: ImportFix[];
}

export interface ImportSummary {
  cards: number;
  sideboard: number;
  notImported: number;
  commander?: string;
  commanderChosen: boolean;
  colors: string;
  verdict?: string;
  main: EditorGroup[];
  sideboardCards: EditorCard[];
}

export interface Fetched {
  site: string;
  url: string;
  text: string;
  format: string;
}

export interface CardPoolLine {
  name: string;
  line: string;
}

export interface SealedBlock {
  name: string;
  packs: number;
  combos: string[];
}

export interface LimitedEdition {
  code: string;
  name: string;
}

export interface DraftBlockOption {
  name: string;
  packs: number;
  sets: string[];
  combos: string[];
  podSize: number;
}

export interface PoolRow {
  name: string;
  built: boolean;
  deckSize: number;
  opponents: Opponent[];
}

export interface DraftSeat {
  name: string;
  ai: boolean;
  packs: number;
  held: boolean;
}

export interface DraftCard {
  name: string;
  image: string;
  cost: string;
  mv: number;
  colors: string;
  type: string;
  pt?: string;
  rarity: string;
  rank?: number;
  pack: number;
  pick: number;
}

export interface RequestOption {
  label: string;
  card?: Ref;
  name?: string;
  imageKey?: string;
  player?: Ref;
}

export interface OrderAnswer {
  indices: number[];
  remember: boolean;
}

export interface SideboardEntry {
  name: string;
  imageKey: string;
  total: number;
}

export type YieldAction = 'autoYield' | 'alwaysYes' | 'alwaysNo' | 'yieldToStack' | 'yieldToEntireStack';

export type DevAction = 'state' | 'unlimitedLands' | 'viewAll' | 'generateMana' | 'tutorForCard' | 'addCardToHand' | 'addCardToBattlefield' | 'addTokenToBattlefield' | 'addCardToLibrary' | 'addCardToGraveyard' | 'addCardToExile' | 'repeatLastAddition' | 'castASpell' | 'exileCardsFromHand' | 'exileCardsFromBattlefield' | 'removeCardsFromGame' | 'addCountersToPermanent' | 'removeCountersFromPermanent' | 'tapPermanents' | 'untapPermanents' | 'setPlayerLife' | 'winGame' | 'rollbackPhase' | 'riggedPlanarRoll' | 'planeswalkTo' | 'setupGameState' | 'dumpGameState';

export type NextGameDecision = 'NEW' | 'CONTINUE' | 'QUIT';

export type Action = 'OFFER' | 'ACCEPT' | 'DECLINE';

export type AutoDecisionAction = 'list' | 'remove' | 'clear' | 'disableYields' | 'disableTriggers';

export type EditOp = 'add' | 'remove' | 'move' | 'commander' | 'printings' | 'lands' | 'landSet' | 'suggestLands';

export type DeckSection = 'Main' | 'Sideboard' | 'Commander' | 'Avatar' | 'Planes' | 'Schemes' | 'Conspiracy' | 'Dungeon' | 'Attractions' | 'Contraptions';

export interface CountedName {
  name: string;
  count: number;
}

export type DeckOp = 'duplicate' | 'delete';

export type ImportAction = 'use' | 'edit' | 'save' | 'add' | 'replace';

export type Clash = 'replace' | 'keep';

export interface DeviceDeckText {
  id: string;
  text: string;
  format: string;
}

export interface Place {
  zone: ZoneType;
  player?: Ref;
}

export interface Attack {
  attacker: Ref;
  defender?: Ref;
}

export type GameLogVerbosity = 'LOW' | 'MEDIUM' | 'HIGH' | 'CUSTOM';

export interface DeckStats {
  main: number;
  sideboard: number;
  lands: number;
  averageMana: number;
  curve: number[];
  types: TypeCount[];
}

export interface EditorGroup {
  heading: string;
  cards: EditorCard[];
}

export interface EditorCard {
  name: string;
  count: number;
  image: string;
  cost: string;
  mv: number;
  colors: string;
  printings: number;
  split: EditorPrinting[];
  problem?: string;
}

export interface Format {
  id: string;
  name: string;
  group: string;
  desc: string;
  facts: string[];
  play: string;
}

export interface CardPoolGroup {
  name: string;
  formats: string[];
}

export interface Seat {
  name?: string;
  type: string;
  mine: boolean;
  mayEdit: boolean;
  ready: boolean;
  avatar: number;
  sleeve: number;
  deck?: string;
  deckName?: string;
  deckSize: number;
  colors: string;
  problem?: string;
  sleeveArt?: string;
  sleeveOffset: number;
  role?: string;
  planes?: SeatExtra;
  schemes?: SeatExtra;
  vanguard?: SeatExtra;
  benched: boolean;
}

export interface LimitedTable {
  kind: string;
  product?: string;
  podSize: number;
  pickRule?: string;
  timer: number;
  phase?: string;
  activeEventId?: string;
  eventDecksOnly: boolean;
  started: boolean;
  pastEvents: PastEvent[];
}

export type ZoneType = 'Hand' | 'Library' | 'Graveyard' | 'Battlefield' | 'Exile' | 'Flashback' | 'Command' | 'Stack' | 'Sideboard' | 'Ante' | 'Merged' | 'SchemeDeck' | 'PlanarDeck' | 'AttractionDeck' | 'Junkyard' | 'ContraptionDeck' | 'Subgame' | 'ExtraHand' | 'None';

export type GameLogEntryType = 'GAME_OUTCOME' | 'MATCH_RESULTS' | 'TURN' | 'MULLIGAN' | 'ANTE' | 'DRAFT' | 'ZONE_CHANGE' | 'PLAYER_CONTROL' | 'DAMAGE' | 'LIFE' | 'LAND' | 'DISCARD' | 'COMBAT' | 'INFORMATION' | 'STACK_RESOLVE' | 'STACK_ADD' | 'EFFECT_REPLACED' | 'MANA' | 'PHASE';

export interface EditorLand {
  name: string;
  letter: string;
  count: number;
  allowed: boolean;
}

export interface LandSet {
  code: string;
  name: string;
}

export interface ImportFix {
  kind: string;
  label: string;
  text?: string;
}

export interface Opponent {
  name: string;
  colors: string;
}

export interface TypeCount {
  name: string;
  count: number;
}

export interface EditorPrinting {
  key: string;
  count: number;
}

export interface SeatExtra {
  label: string;
  count: number;
  detail?: string;
  problem?: string;
}

export interface PastEvent {
  id: string;
  label: string;
}

// ---- Game objects: TrackableProperty values as JsonCodec encodes them ----

/** One attack: who attacks what, and who blocks it. */
export interface CombatBand {
  attackers: (Ref | null)[] | null;
  defender: Ref | null;
  blockers: (Ref | null)[] | null;
  plannedBlockers: (Ref | null)[] | null;
}

export interface CommanderValue {
  card: Ref;
  value: number;
}

export interface KeywordText {
  title: string;
  reminder: string;
  icon?: string;
}

/** Every property any game object can carry. A property still at its default is left out. */
export interface TrackedProps {
  PreventNextDamage?: number;
  AttachedCards?: (Ref | null)[];
  Counters?: Record<string, number>;
  CurrentPlane?: string;
  PlanarPlayer?: Ref;
  Owner?: Ref;
  Controller?: Ref;
  Zone?: ZoneType;
  GamePieceType?: GamePieceType;
  IsEmblem?: boolean;
  IsBoon?: boolean;
  CanSpecialize?: boolean;
  Flipped?: boolean;
  Facedown?: boolean;
  Foretold?: boolean;
  Modal?: boolean;
  Secondary?: boolean;
  DoubleFaced?: boolean;
  FacedownImageKey?: string;
  PaperFoil?: boolean;
  Cloner?: string;
  Cloned?: boolean;
  FlipCard?: boolean;
  SplitCard?: boolean;
  MergedCards?: string;
  MergedCardsCollection?: (Ref | null)[];
  RevealedCardsCollection?: (Ref | null)[];
  PaperCardBackup?: { name: string; imageKey: string };
  Attacking?: boolean;
  Blocking?: boolean;
  PhasedOut?: boolean;
  Sickness?: boolean;
  Tapped?: boolean;
  Token?: boolean;
  TokenCard?: boolean;
  IsCommander?: boolean;
  IsRingBearer?: boolean;
  CommanderAltType?: string;
  Damage?: number;
  AssignedDamage?: number;
  LethalDamage?: number;
  ShieldCount?: number;
  ChosenType?: string;
  ChosenType2?: string;
  NotedTypes?: string[];
  ChosenColors?: string[];
  ChosenCards?: (Ref | null)[];
  ChosenNumber?: string;
  StoredRolls?: string[];
  ChosenPlayer?: Ref;
  PromisedGift?: Ref;
  ProtectingPlayer?: Ref;
  ChosenDirection?: Direction;
  ChosenEvenOdd?: EvenOdd;
  ChosenMode?: string;
  Sector?: string;
  Sprocket?: number;
  DraftAction?: string[];
  ClassLevel?: number;
  RingLevel?: number;
  CurrentRoom?: string;
  Intensity?: number;
  OverlayText?: string;
  MarkerText?: string[];
  Remembered?: string;
  NamedCard?: string[];
  PlayerMayLook?: (Ref | null)[];
  EntityAttachedTo?: Ref;
  EncodedCards?: (Ref | null)[];
  UntilLeavesBattlefield?: (Ref | null)[];
  GainControlTargets?: (Ref | null)[];
  CloneOrigin?: Ref;
  ExiledWith?: Ref;
  PreparedSpell?: Ref;
  WasDestroyed?: boolean;
  NeedsTransformAnimation?: boolean;
  NeedsUntapAnimation?: boolean;
  NeedsTapAnimation?: boolean;
  MarkedColors?: number;
  ImprintedCards?: (Ref | null)[];
  ExiledCards?: (Ref | null)[];
  HauntedBy?: (Ref | null)[];
  Haunting?: Ref;
  MustBlockCards?: (Ref | null)[];
  PairedWith?: Ref;
  CurrentState?: Ref;
  AlternateState?: Ref;
  LeftSplitState?: Ref;
  RightSplitState?: Ref;
  Room?: boolean;
  HiddenId?: number;
  ExertedThisTurn?: boolean;
  Detained?: boolean;
  Name?: string;
  Colors?: number;
  OriginalColors?: number;
  ImageKey?: string;
  Type?: string;
  ManaCost?: string;
  OriginalManaCost?: string;
  SetCode?: string;
  Rarity?: CardRarity;
  FunctionalVariant?: string;
  OracleText?: string;
  RulesText?: string;
  OracleName?: string;
  Power?: number;
  Toughness?: number;
  Loyalty?: string;
  Defense?: string;
  AttractionLights?: number[];
  ChangedColorWords?: Record<string, string>;
  HasChangedColors?: boolean;
  HasPrintedPT?: boolean;
  ChangedTypes?: Record<string, string>;
  OrigProduceMana?: number;
  OrigProduceAnyMana?: boolean;
  Keywords?: KeywordText[];
  HasAnnihilator?: boolean;
  HasWard?: boolean;
  BlockAdditional?: number;
  BlockAny?: boolean;
  AbilityText?: string;
  NonAbilityText?: string;
  HasDivideDamage?: boolean;
  FoilIndex?: number;
  CantHaveKeyword?: string[];
  IsAI?: boolean;
  LobbyPlayerName?: string;
  AvatarIndex?: number;
  AvatarCardImageKey?: string;
  SleeveIndex?: number;
  SleeveArtKey?: string;
  SleeveArtOffset?: number;
  Opponents?: (Ref | null)[];
  Life?: number;
  MaxHandSize?: number;
  HasUnlimitedHandSize?: boolean;
  MaxLandPlay?: number;
  HasUnlimitedLandPlay?: boolean;
  NumLandThisTurn?: number;
  NumManaShards?: number;
  DraftNotes?: Record<string, string>;
  NumDrawnThisTurn?: number;
  AdditionalVote?: number;
  OptionalAdditionalVote?: number;
  ControlVotes?: boolean;
  AdditionalVillainousChoices?: number;
  Commander?: (Ref | null)[];
  CommanderCast?: CommanderValue[];
  CommanderDamage?: CommanderValue[];
  MindSlaveMaster?: Ref;
  Ante?: (Ref | null)[];
  Battlefield?: (Ref | null)[];
  Command?: (Ref | null)[];
  Exile?: (Ref | null)[];
  Flashback?: (Ref | null)[];
  Graveyard?: (Ref | null)[];
  Hand?: (Ref | null)[];
  Library?: (Ref | null)[];
  Sideboard?: (Ref | null)[];
  PlanarDeck?: (Ref | null)[];
  SchemeDeck?: (Ref | null)[];
  AttractionDeck?: (Ref | null)[];
  ContraptionDeck?: (Ref | null)[];
  Junkyard?: (Ref | null)[];
  Mana?: Record<string, number>;
  IsExtraTurn?: boolean;
  ExtraTurnCount?: number;
  HasPriority?: boolean;
  AvatarLifeDifference?: number;
  HasLost?: boolean;
  HasAvailableActions?: boolean;
  HostCard?: Ref;
  Description?: string;
  CanPlay?: boolean;
  PromptIfOnlyPossibleAbility?: boolean;
  SA_IsSpell?: boolean;
  Key?: string;
  SourceTrigger?: number;
  SourceCard?: Ref;
  ActivatingPlayer?: Ref;
  TargetCards?: (Ref | null)[];
  TargetPlayers?: (Ref | null)[];
  SubInstance?: Ref;
  Ability?: boolean;
  OptionalTrigger?: boolean;
  OptionalCosts?: string;
  AttackersWithDefenders?: unknown;
  AttackersWithBlockers?: unknown;
  BandsWithDefenders?: unknown;
  BandsWithBlockers?: unknown;
  AttackersWithPlannedBlockers?: unknown;
  BandsWithPlannedBlockers?: unknown;
  CombatView?: CombatBand[];
  Players?: (Ref | null)[];
  GameType?: GameType;
  Title?: string;
  Turn?: number;
  WinningPlayerName?: string;
  WinningTeam?: number;
  MatchOver?: boolean;
  Mulligan?: boolean;
  NumGamesInMatch?: number;
  NumPlayedGamesInMatch?: number;
  Stack?: (Ref | null)[];
  StormCount?: number;
  GameOver?: boolean;
  PoisonCountersToLose?: number;
  PlayerTurn?: Ref;
  Phase?: PhaseType;
  Object?: unknown;
  Dependencies?: string;
}

export type GamePieceType = 'CARD' | 'TOKEN' | 'EFFECT' | 'COPIED_SPELL' | 'ATTRACTION' | 'CONTRAPTION' | 'PLANAR' | 'SCHEME' | 'AVATAR' | 'DUNGEON';

export type Direction = 'Left' | 'Right';

export type EvenOdd = 'Even' | 'Odd';

export type CardRarity = 'BasicLand' | 'Common' | 'Uncommon' | 'Rare' | 'MythicRare' | 'Special' | 'Token' | 'Unknown';

export type GameType = 'Sealed' | 'Draft' | 'Winston' | 'Gauntlet' | 'Tournament' | 'CommanderGauntlet' | 'Quest' | 'QuestCommander' | 'QuestDraft' | 'PlanarConquest' | 'Adventure' | 'AdventureEvent' | 'Puzzle' | 'Constructed' | 'DeckManager' | 'Vanguard' | 'Commander' | 'Oathbreaker' | 'TinyLeaders' | 'Brawl' | 'Planeswalker' | 'Planechase' | 'Archenemy' | 'ArchenemyRumble' | 'MomirBasic' | 'MoJhoSto';

/** A change to an object: a property set to null has gone back to its default. */
export type TrackedDelta = { [K in keyof TrackedProps]?: TrackedProps[K] | null };
