package forge.web;

import java.io.IOException;
import java.io.Reader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;
import java.util.TreeSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;

/** Finds the language keys the page uses, and fails the build on a page key en-US.properties lacks or one with a lone apostrophe. */
final class PageTextKeys {
    private static final Pattern QUOTED_KEY = Pattern.compile("['\"]([a-z]{2,4}[A-Z][A-Za-z0-9]*)['\"]");
    private static final Pattern OWN_KEY = Pattern.compile("[a-z]+Web[A-Z][A-Za-z0-9]*");
    private static final Pattern LONE_QUOTE = Pattern.compile("(?<!')'(?!')");

    private PageTextKeys() {
    }

    static void write(final Path tsDir, final Path languagesDir, final Path classesDir) throws IOException {
        final Properties english = new Properties();
        try (Reader in = Files.newBufferedReader(languagesDir.resolve("en-US.properties"), StandardCharsets.UTF_8)) {
            english.load(in);
        }
        final TreeSet<String> used = new TreeSet<>();
        final List<String> problems = new ArrayList<>();
        final List<Path> sources = new ArrayList<>();
        try (Stream<Path> files = Files.list(tsDir)) {
            files.filter(f -> f.toString().matches(".*\\.tsx?") && !f.toString().endsWith(".gen.ts")).sorted().forEach(sources::add);
        }
        // The page's frame names some of its text too, by data-text
        sources.add(tsDir.resolve("../resources/web/index.html").normalize());
        for (final Path file : sources) {
            final Matcher m = QUOTED_KEY.matcher(Files.readString(file, StandardCharsets.UTF_8));
            while (m.find()) {
                final String key = m.group(1);
                final String pattern = english.getProperty(key);
                if (pattern != null) {
                    used.add(key);
                    if (OWN_KEY.matcher(key).matches() && LONE_QUOTE.matcher(pattern).find()) {
                        problems.add(key + " has a single ' in en-US.properties; write it as ''");
                    }
                } else if (OWN_KEY.matcher(key).matches()) {
                    problems.add(file.getFileName() + " uses " + key + ", which en-US.properties does not have");
                }
            }
        }
        if (!problems.isEmpty()) {
            throw new IllegalStateException("The page's text does not match en-US.properties:\n  " + String.join("\n  ", problems));
        }

        final StringBuilder ts = new StringBuilder()
                .append("// Generated by forge.web.PageTextKeys from the keys the page uses that forge-gui/res/languages/en-US.properties\n")
                .append("// has. Do not edit: Maven writes it again.\n\n")
                .append("export type TextKey =");
        if (used.isEmpty()) {
            ts.append(" never");
        }
        for (final String key : used) {
            ts.append("\n  | '").append(key).append('\'');
        }
        ts.append(";\n");
        writeIfChanged(tsDir.resolve("text.gen.ts"), ts.toString());
        writeIfChanged(classesDir.resolve(PageText.KEYS_RESOURCE.substring(1)), String.join("\n", used) + "\n");
    }

    /** Left alone when unchanged, so a watching build has nothing to rebuild. */
    static void writeIfChanged(final Path file, final String text) throws IOException {
        if (!Files.isRegularFile(file) || !Files.readString(file, StandardCharsets.UTF_8).equals(text)) {
            Files.createDirectories(file.getParent());
            Files.writeString(file, text, StandardCharsets.UTF_8);
        }
    }
}
